- hosts: k8s
  become: true
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg2']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
  
  - name: Add user ucloud ao grupo docker
    user:
      name: ucloud
      group: docker
      append: true
  
  - name: Disable SWAP (1/2)
    shell: |
      swapoff -a
  
  - name: Disable SWAP in fstab (2/2)
    replace:
      path: /etc/fstab
      regexp: '^(.+?\sswap\s+sw\s+.*)$'
      replace: '# \1'

  - name:  Add google package  repo key
    apt_key:
      url:  https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

#  - name: Add google package key
#    shell:  'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -' 

  - name: Add kubernetes.lis to apt source list
    lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: ['kubelet', 'kubeadm', 'kubectl']

  - name: Install Kube-api-server
    snap:
      name: kube-apiserver

  - name: Install kube-controller-manager
    snap:
      name: kube-controller-manager

  - name: Install kube-scheduler
    snap:
      name: kube-scheduler

  - name: Install kube-proxy
    snap: 
      name: kube-proxy
      classic: yes
